CSRF_ENABLED = True
SECRET_KEY = ''
RECAPTCHA_PUBLIC_KEY = ''
RECAPTCHA_PRIVATE_KEY = ''
RECAPTCHA_OPTIONS = {'theme': 'blackglass'}

PROD_DB_URL = ''
DEV_DB_URL = ''

CROC_API_TOKEN = ''

BUCKET_NAME = ''

AWS_ACCESS_KEY = ''
AWS_SECRET_KEY = ''

MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USERNAME = ''
MAIL_PASSWORD = ''

ADMINS = []

DEBUG = True